language: node_js
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _book
  on:
    branch: master
